import React from 'react'
import {Check, Clock3, Plus, Search, X} from 'lucide-react'
import {SeedUser, UserType, userTypes, users} from './data'
import {addManualVisit,getAllVisits} from './attendanceStore'
import {loadSettings} from './settings'
const localInput=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
export default function Attendance(){
 const[q,setQ]=React.useState(''),[type,setType]=React.useState('All'),[year,setYear]=React.useState('All'),[version,setVersion]=React.useState(0),[manual,setManual]=React.useState(()=>new URLSearchParams(location.search).get('manual')==='1')
 const closeManual=()=>{setManual(false);if(location.search)history.replaceState({},'',location.pathname)}
 const rows=React.useMemo(()=>getAllVisits().filter(v=>(type==='All'||v.userType===type)&&(year==='All'||v.academicYear===year)&&(v.visitor+' '+v.studentNumber).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.timeIn.localeCompare(a.timeIn)),[q,type,year,version])
 return <div className="module-stack"><div className="module-heading"><div><span className="eyebrow">Check-in log</span><h2>Library attendance</h2><p>QR and librarian-recorded check-ins share one attendance log.</p></div><div className="attendance-heading-actions"><div className="module-count"><Clock3 size={18}/><strong>{rows.length}</strong><span>check-ins</span></div><button className="manual-button" onClick={()=>setManual(true)}><Plus size={17}/>Manual check-in</button></div></div><section className="panel"><div className="module-filters"><label className="module-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search user"/></label><select value={type} onChange={e=>setType(e.target.value)}><option>All</option>{userTypes.map(x=><option key={x}>{x}</option>)}</select><select value={year} onChange={e=>setYear(e.target.value)}><option>All</option><option>2026-2027</option><option>2025-2026</option></select></div><div className="table-wrap attendance-table"><table><thead><tr><th>Date</th><th>User</th><th>Type</th><th>Program / Department</th><th>Check-in time</th><th>Source</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td>{v.date}</td><td><strong>{v.visitor}</strong><small>{v.studentNumber}</small>{v.note&&<small>{v.note}</small>}</td><td>{v.userType}</td><td>{v.userType==='Student'?v.program:v.department}</td><td>{new Date(v.timeIn).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td><td><span className={v.source==='manual'?'badge manual':'badge inside'}>{v.source==='manual'?'Manual':'QR check-in'}</span></td></tr>)}</tbody></table></div></section>{manual&&<ManualModal close={closeManual} saved={()=>{setVersion(v=>v+1);closeManual()}}/>}</div>
}
function ManualModal({close,saved}:{close:()=>void;saved:()=>void}){
 const settings=loadSettings(),[userType,setUserType]=React.useState<UserType>('Student'),[number,setNumber]=React.useState(''),[visitor,setVisitor]=React.useState({name:'',organization:'',purpose:''}),[timeMode,setTimeMode]=React.useState<'now'|'manual'>('now'),[time,setTime]=React.useState(localInput),[note,setNote]=React.useState('')
 const available=users.filter(u=>u.userType===userType&&u.userType!=='Visitor'),selected=available.find(u=>u.number===number)||available[0]
 React.useEffect(()=>setNumber(''),[userType])
 function submit(e:React.FormEvent){e.preventDefault();const at=timeMode==='now'?new Date():new Date(time);let user:SeedUser;if(userType==='Visitor')user={name:visitor.name,number:'VIS-'+Date.now().toString().slice(-6),userType:'Visitor',program:'',yearLevel:'',section:'',department:visitor.organization||'External Visitor'};else if(selected)user=selected;else return;addManualVisit({id:Date.now(),date:at.toISOString().slice(0,10),academicYear:settings.academicYear,semester:settings.semester,userType:user.userType,yearLevel:user.yearLevel,section:user.section,program:user.program,department:user.department,visitor:user.name,studentNumber:user.number,timeIn:at.toISOString(),source:'manual',note:userType==='Visitor'?[visitor.purpose,note].filter(Boolean).join(' · '):note});saved()}
 return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="manual-modal" onSubmit={submit}><header><div><span className="eyebrow">Librarian entry</span><h3>Manual check-in</h3><p>Record attendance when a QR scan is unavailable.</p></div><button type="button" className="icon-button" onClick={close} title="Close"><X size={19}/></button></header><div className="manual-form"><label>User type<select value={userType} onChange={e=>setUserType(e.target.value as UserType)}>{userTypes.map(t=><option key={t}>{t}</option>)}</select></label>{userType==='Visitor'?<><label>Visitor name<input value={visitor.name} onChange={e=>setVisitor(v=>({...v,name:e.target.value}))} required/></label><label>Organization<input value={visitor.organization} onChange={e=>setVisitor(v=>({...v,organization:e.target.value}))}/></label><label>Purpose of visit<input value={visitor.purpose} onChange={e=>setVisitor(v=>({...v,purpose:e.target.value}))} required/></label></>:<label className="wide">User<select value={selected?.number||''} onChange={e=>setNumber(e.target.value)}>{available.map(u=><option value={u.number} key={u.number}>{u.name} · {u.number}</option>)}</select>{selected&&<small>{selected.userType==='Student'?[selected.program,selected.yearLevel,selected.section].join(' · '):selected.department}</small>}</label>}<div className="time-choice wide"><span>Check-in date and time</span><div className="time-segments"><button type="button" className={timeMode==='now'?'active':''} onClick={()=>setTimeMode('now')}>Automatic / now</button><button type="button" className={timeMode==='manual'?'active':''} onClick={()=>{setTimeMode('manual');setTime(localInput())}}>Set manually</button></div>{timeMode==='now'?<small>The current date and time will be recorded when you submit.</small>:<input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} max={localInput()} required/>}</div><label>Note (optional)<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Reason for manual entry"/></label></div><footer><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="save-button"><Check size={16}/>Record check-in</button></footer></form></div>
}


