import React from 'react'
import {Download, Filter} from 'lucide-react'
import ExcelJS from 'exceljs'
import {jsPDF} from 'jspdf'
import autoTable from 'jspdf-autotable'
import {departments,programs,sections,userTypes,years} from './data'
import {getAllVisits,StoredVisit} from './attendanceStore'
import {loadSettings} from './settings'

type Filters={dateFrom:string;dateTo:string;academicYear:string;semester:string;period:string;userType:string;yearLevel:string;section:string;program:string;department:string}
const baseFilters:Filters={dateFrom:'',dateTo:'',academicYear:'All',semester:'All',period:'Monthly',userType:'All',yearLevel:'All',section:'All',program:'All',department:'All'}
const options={academicYear:['All','2026-2027','2025-2026'],semester:['All','1st Semester','2nd Semester','Summer'],period:['Daily','Weekly','Monthly','Annual'],userType:['All',...userTypes],yearLevel:['All',...years],section:['All',...sections],program:['All',...programs],department:['All',...departments]}
const label:Record<string,string>={dateFrom:'Date from',dateTo:'Date to',academicYear:'Academic Year',semester:'Semester',period:'Trend grouping',userType:'User Type',yearLevel:'Year Level / Intake',section:'Section',program:'Degree Program',department:'Staff Department'}
function countBy<T>(rows:T[],key:(row:T)=>string){return Object.entries(rows.reduce<Record<string,number>>((a,row)=>{const k=key(row)||'Not specified';a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>a[0].localeCompare(b[0]))}
function weekKey(date:string){const d=new Date(date+'T00:00:00'),start=new Date(d);start.setDate(d.getDate()-d.getDay());return start.toISOString().slice(0,10)}
function trendKey(date:string,period:string){const d=new Date(date+'T00:00:00');if(period==='Daily')return date;if(period==='Weekly')return weekKey(date);if(period==='Annual')return String(d.getFullYear());return date.slice(0,7)}
function top(entries:[string,number][],limit=8){return [...entries].sort((a,b)=>b[1]-a[1]).slice(0,limit)}
function reportDate(value:string){return value?new Date(value+'T00:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}):'No records'}
function userCategory(v:StoredVisit){return v.userType==='Student'?'Student':v.userType==='Faculty'?'Faculty / Teaching Personnel':v.userType==='Non-Teaching'?'Non-Teaching Personnel':v.userType==='Visitor'?'Visitor':'Administrator'}
const excelColors={maroon:'FF690F0D',teal:'FF00A5B7',ivory:'FFF2E8DC',white:'FFFFFFFF',line:'FFD7D9DD',text:'FF202329'}
function styleExcelSheet(ws:any,summary:boolean){
 const thin={style:'thin',color:{argb:excelColors.line}},sections=['Complete Report Details','Summary Statistics','User Categories','Student Breakdown'],tables=['Measure','Category','Dimension']
 ws.eachRow((row:any,rowNumber:number)=>{row.height=rowNumber===1?summary?29:25:19;row.eachCell({includeEmpty:false},(cell:any)=>{cell.font={name:'Aptos',size:10,color:{argb:excelColors.text}};cell.alignment={vertical:'middle',wrapText:true};cell.border={top:thin,bottom:thin,left:thin,right:thin};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:rowNumber%2?excelColors.white:'FFFBF8F4'}};if(typeof cell.value==='number')cell.numFmt='#,##0'})})
 const header=(rowNumber:number,color:string)=>{const row=ws.getRow(rowNumber);row.height=24;row.eachCell({includeEmpty:true},(cell:any)=>{cell.font={name:'Aptos Display',size:10,bold:true,color:{argb:excelColors.white}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:color}};cell.alignment={vertical:'middle',wrapText:true};cell.border={top:thin,bottom:thin,left:thin,right:thin}})}
 if(summary){ws.mergeCells('A1:C1');header(1,excelColors.maroon);ws.getCell('A1').font={name:'Aptos Display',size:17,bold:true,color:{argb:excelColors.white}};ws.eachRow((row:any,n:number)=>{const value=String(row.getCell(1).value||'');if(sections.includes(value)){ws.mergeCells(n,1,n,3);header(n,excelColors.maroon)}else if(tables.includes(value))header(n,excelColors.teal)})}
 else{header(1,excelColors.maroon);ws.autoFilter={from:{row:1,column:1},to:{row:ws.rowCount,column:ws.columnCount}};ws.columns.forEach((column:any)=>{let max=11;column.eachCell({includeEmpty:true},(cell:any)=>{max=Math.max(max,Math.min(40,String(cell.value??'').length+2))});column.width=max})}
}
function chartPng(title:string,entries:[string,number][],kind:'line'|'pie'|'bar'){
 const canvas=document.createElement('canvas');canvas.width=1440;canvas.height=540;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#690f0d';ctx.font='bold 32px Arial';ctx.fillText(title,45,48);ctx.font='18px Arial';ctx.fillStyle='#6b7280';ctx.fillText('Life College Library Attendance',45,78);const data=entries.length?entries:[['No data',0] as [string,number]],colors=['#690f0d','#00a5b7','#e0a72e','#9e1d20','#65717e','#4d8f62']
 if(kind==='pie'){const total=Math.max(1,data.reduce((a,e)=>a+e[1],0)),cx=350,cy=305,r=165;let angle=-Math.PI/2;data.forEach((entry,i)=>{const end=angle+entry[1]/total*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,angle,end);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();angle=end});data.forEach((entry,i)=>{const y=150+i*60;ctx.fillStyle=colors[i%colors.length];ctx.fillRect(700,y,24,24);ctx.fillStyle='#202329';ctx.font='20px Arial';ctx.fillText(entry[0].slice(0,38),740,y+20);ctx.font='bold 20px Arial';ctx.fillText(String(entry[1]),1250,y+20)})}
 else if(kind==='line'){const max=Math.max(1,...data.map(e=>e[1])),left=75,right=1370,topY=115,bottom=455;ctx.strokeStyle='#d7d9dd';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(left,topY);ctx.lineTo(left,bottom);ctx.lineTo(right,bottom);ctx.stroke();ctx.strokeStyle='#00a5b7';ctx.lineWidth=6;ctx.beginPath();data.forEach((e,i)=>{const x=data.length===1?(left+right)/2:left+i/(data.length-1)*(right-left),y=bottom-e[1]/max*(bottom-topY);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();data.forEach((e,i)=>{const x=data.length===1?(left+right)/2:left+i/(data.length-1)*(right-left),y=bottom-e[1]/max*(bottom-topY);ctx.fillStyle='#690f0d';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#6b7280';ctx.font='16px Arial';ctx.fillText(data[0][0],left,bottom+35);ctx.textAlign='right';ctx.fillText(data.at(-1)![0],right,bottom+35);ctx.textAlign='left'}
 else{const shown=data.slice(0,12),max=Math.max(1,...shown.map(e=>e[1]));shown.forEach((e,i)=>{const y=105+i*34;ctx.fillStyle='#202329';ctx.font='15px Arial';ctx.fillText(e[0].slice(0,46),45,y+18);ctx.fillStyle='#edf0f2';ctx.fillRect(520,y,790,22);ctx.fillStyle=colors[i%2];ctx.fillRect(520,y,790*e[1]/max,22);ctx.fillStyle='#202329';ctx.font='bold 15px Arial';ctx.fillText(String(e[1]),1330,y+18)})}
 return canvas.toDataURL('image/png')
}

export default function Reports(){
 const seed=React.useMemo(getAllVisits,[]),settings=loadSettings()
 const initial=React.useMemo(()=>({...baseFilters,period:settings.defaultReportPeriod,userType:settings.defaultReportUserType}),[])
 const[filters,setFilters]=React.useState<Filters>(initial)
 const rows=React.useMemo(()=>seed.filter(v=>(!filters.dateFrom||v.date>=filters.dateFrom)&&(!filters.dateTo||v.date<=filters.dateTo)&&(filters.academicYear==='All'||v.academicYear===filters.academicYear)&&(filters.semester==='All'||v.semester===filters.semester)&&(filters.userType==='All'||v.userType===filters.userType)&&(filters.yearLevel==='All'||v.yearLevel===filters.yearLevel)&&(filters.section==='All'||v.section===filters.section)&&(filters.program==='All'||v.program===filters.program)&&(filters.department==='All'||v.department===filters.department)),[seed,filters])
 const unique=new Set(rows.map(v=>v.studentNumber)).size
 const daily=countBy(rows,v=>v.date),weekly=countBy(rows,v=>weekKey(v.date)),monthly=countBy(rows,v=>v.date.slice(0,7)),semesters=countBy(rows,v=>v.academicYear+' · '+v.semester)
 const yearSection=countBy(rows,v=>v.userType==='Student'?[v.yearLevel,v.section].filter(Boolean).join(' · '):'Non-student')
 const sectionUsage=countBy(rows,v=>v.userType==='Student'?v.section:'Non-student'),programUsage=countBy(rows,v=>v.userType==='Student'?v.program:'Non-student')
 const categoryCounts=Object.fromEntries(countBy(rows,userCategory)),categories:[string,number][]= ['Student','Faculty / Teaching Personnel','Non-Teaching Personnel','Administrator','Visitor'].map(name=>[name,categoryCounts[name]||0])
 const hours=countBy(rows,v=>new Date(v.timeIn).toLocaleTimeString([],{hour:'2-digit'})),weekdays=countBy(rows,v=>new Date(v.date+'T00:00:00').toLocaleDateString(undefined,{weekday:'long'}))
 const trend=countBy(rows,v=>trendKey(v.date,filters.period))
 const average=(entries:[string,number][])=>entries.length?rows.length/entries.length:0
 const peakDay=top(daily,1)[0],peakWeekday=top(weekdays,1)[0],peakHour=top(hours,1)[0]
 const userVisitCounts=Object.values(rows.reduce<Record<string,number>>((a,v)=>{a[v.studentNumber]=(a[v.studentNumber]||0)+1;return a},{})),returningUsers=userVisitCounts.filter(count=>count>1).length
 const studentRows=rows.filter(v=>v.userType==='Student'),studentPrograms=countBy(studentRows,v=>v.program),studentYears=countBy(studentRows,v=>v.yearLevel),studentSections=countBy(studentRows,v=>v.section)
 const academicYears=filters.academicYear==='All'?[...new Set(rows.map(v=>v.academicYear))].sort().join(', ')||'All academic years':filters.academicYear
 const semesterDetail=filters.semester==='All'?[...new Set(rows.map(v=>v.semester))].sort().join(', ')||'All semesters':filters.semester
 const periodStart=filters.dateFrom||daily[0]?.[0]||'',periodEnd=filters.dateTo||daily.at(-1)?.[0]||'',reportingPeriod=periodStart===periodEnd?reportDate(periodStart):`${reportDate(periodStart)} - ${reportDate(periodEnd)}`
 const filterSummary=Object.entries(filters).filter(([,v])=>v&&v!=='All').map(([k,v])=>`${label[k]}: ${v}`).join(' | ')||'All available records'
 const exportRows=rows.map(v=>({'Date':v.date,'Academic Year':v.academicYear,'Semester':v.semester,'Name':v.visitor,'ID Number':v.studentNumber,'User Type':v.userType,'Year Level':v.yearLevel,'Section':v.section,'Degree Program':v.program,'Department':v.department,'Source':v.source==='manual'?'Manual':'QR','Note':v.note||'','Check-in Time':new Date(v.timeIn).toLocaleTimeString()}))
 function exportExcel(){
  const workbook=new ExcelJS.Workbook();workbook.creator='Life College';workbook.company='Life College';workbook.title='Life College Library Attendance Report';workbook.created=new Date()
  const summaryRows:(string|number)[][]=[['Life College Library Attendance Report','',''],[],['Complete Report Details','',''],['Academic Year',academicYears,''],['Semester',semesterDetail,''],['Reporting Period / Date Range',reportingPeriod,''],['Trend Grouping',filters.period,''],['Date and Time Generated',new Date().toLocaleString(),''],[],['Summary Statistics','',''],['Measure','Value','Definition'],['Total Library Visits',rows.length,'All check-ins in the selected period'],['Unique Users',unique,'Distinct ID numbers'],['Return Visits',Math.max(0,rows.length-unique),'Visits beyond each user’s first visit'],['Returning Users',returningUsers,'Users with more than one visit'],['Average Visits per Open Day',average(daily).toFixed(2),`${daily.length} open days`],['Average Visits per User',unique?(rows.length/unique).toFixed(2):'0.00','Total visits divided by unique users'],[],['User Categories','',''],['Category','Visits','Share of visits'],...categories.map(([name,count])=>[name,count,rows.length?`${(count/rows.length*100).toFixed(1)}%`:'0.0%']),[],['Student Breakdown','',''],['Dimension','Program / Year Level / Section','Visits'],...top(studentPrograms,100).map(([name,count])=>['Program / Course',name,count]),...top(studentYears,100).map(([name,count])=>['Year Level',name,count]),...top(studentSections,100).map(([name,count])=>['Section',name,count])]
  const executive=workbook.addWorksheet('Executive Summary',{views:[{state:'frozen',ySplit:1}]});executive.addRows(summaryRows);executive.columns=[{width:34},{width:55},{width:42},{width:3},...Array.from({length:8},()=>({width:13}))]
  styleExcelSheet(executive,true)
  const charts=[chartPng('Attendance Trend',trend,'line'),chartPng('Visits per User Category',categories,'pie'),chartPng('Student Visits by Program, Year Level, and Section',[...top(studentPrograms,5).map(([k,v])=>['Program: '+k,v] as [string,number]),...top(studentYears,4).map(([k,v])=>['Year: '+k,v] as [string,number]),...top(studentSections,4).map(([k,v])=>['Section: '+k,v] as [string,number])],'bar')]
  ;[['E2','L17'],['E19','L34'],['E36','L52']].forEach(([tl,br],i)=>{const id=workbook.addImage({base64:charts[i],extension:'png'});executive.addImage(id,{tl:{col:4,row:[1,18,35][i]},ext:{width:720,height:270}})})
  const addData=(name:string,headers:string[],data:(string|number)[][])=>{const ws=workbook.addWorksheet(name,{views:[{state:'frozen',ySplit:1}]});ws.addRow(headers);ws.addRows(data);styleExcelSheet(ws,false);return ws}
  addData('Check-ins',Object.keys(exportRows[0]||{'No records':''}),exportRows.map(r=>Object.values(r)))
  addData('Daily Traffic',['Date','Visits'],daily);addData('Weekly Traffic',['Week starting','Visits'],weekly);addData('Monthly Traffic',['Month','Visits'],monthly);addData('Year and Section',['Year level and section','Visits'],top(yearSection,100));addData('Section Usage',['Section','Visits'],top(sectionUsage,100));addData('Program Usage',['Program','Visits'],top(programUsage,100));addData('Semester Comparison',['Academic year and semester','Visits'],semesters);addData('User Categories',['Category','Visits'],categories);addData('Peak Hours',['Hour','Visits'],top(hours,100))
  workbook.xlsx.writeBuffer().then(buffer=>{const blob=new Blob([buffer as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='life-college-library-accreditation-report.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})
 }
 function exportPdf(){
  const doc=new jsPDF({orientation:'landscape'}),maroon=[105,15,13] as [number,number,number],teal=[0,165,183] as [number,number,number]
  doc.setTextColor(...maroon);doc.setFontSize(19);doc.text('Life College Library Attendance Report',14,15);doc.setTextColor(70);doc.setFontSize(8);doc.text(filterSummary.slice(0,180),14,21)
  autoTable(doc,{startY:27,head:[['Measure','Value']],body:[['Total visits',rows.length],['Unique visitors',unique],['Repeat visits',Math.max(0,rows.length-unique)],['Average daily',average(daily).toFixed(2)],['Average weekly',average(weekly).toFixed(2)],['Average monthly',average(monthly).toFixed(2)],['Peak date',peakDay?peakDay.join(' · '):'-'],['Peak hour',peakHour?peakHour.join(' · '):'-']],theme:'grid',headStyles:{fillColor:maroon},tableWidth:120})
  doc.setFontSize(12);doc.setTextColor(...maroon);doc.text('Usage by category',155,31);drawBars(doc,categories,155,36,110,teal)
  doc.addPage();doc.setFontSize(16);doc.text('Attendance trend and utilization',14,15);drawLine(doc,trend,14,24,130,64,teal);drawBars(doc,top(programUsage,7),158,24,110,maroon)
  autoTable(doc,{startY:100,head:[['Year level / Section','Visits'],['Program','Visits'],['Semester','Visits']],body:Array.from({length:Math.max(8,yearSection.length,programUsage.length,semesters.length)},(_,i)=>[top(yearSection,8)[i]?.join(' · ')||'',top(programUsage,8)[i]?.join(' · ')||'',top(semesters,8)[i]?.join(' · ')||'']),styles:{fontSize:7},headStyles:{fillColor:maroon}})
  doc.addPage();doc.setFontSize(16);doc.text('Filtered check-in records',14,15);autoTable(doc,{startY:21,head:[Object.keys(exportRows[0]||{'No records':''})],body:exportRows.map(r=>Object.values(r)),styles:{fontSize:5.5},headStyles:{fillColor:teal},horizontalPageBreak:true});doc.save('life-college-library-accreditation-report.pdf')
 }
 const maxTrend=Math.max(1,...trend.map(x=>x[1])),catTotal=Math.max(1,categories.reduce((a,x)=>a+x[1],0));let pieStop=0
 return <div className="reports-page space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Library usage reports</h1><p className="mt-1 text-sm text-zinc-500">Accreditation-ready traffic, utilization, and attendance analysis.</p></div><div className="flex gap-2"><button onClick={exportExcel} className="flex items-center gap-2 border border-zinc-300 px-3 py-2 text-sm"><Download size={16}/>Excel workbook</button><button onClick={exportPdf} className="flex items-center gap-2 bg-zinc-900 px-3 py-2 text-sm text-white"><Download size={16}/>PDF report</button></div></div>
 <section className="border border-zinc-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 font-semibold"><Filter size={18}/>Report filters</div><button onClick={()=>setFilters(initial)} className="report-reset text-sm">Reset</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium">Date from<input type="date" value={filters.dateFrom} max={filters.dateTo||undefined} onChange={e=>setFilters(f=>({...f,dateFrom:e.target.value}))} className="mt-2 w-full border border-zinc-300 bg-white px-3 py-2.5 font-normal"/></label><label className="text-sm font-medium">Date to<input type="date" value={filters.dateTo} min={filters.dateFrom||undefined} onChange={e=>setFilters(f=>({...f,dateTo:e.target.value}))} className="mt-2 w-full border border-zinc-300 bg-white px-3 py-2.5 font-normal"/></label>{Object.entries(options).map(([key,values])=><label key={key} className="text-sm font-medium">{label[key]}<select value={filters[key as keyof Filters]} onChange={e=>setFilters(f=>({...f,[key]:e.target.value}))} className="mt-2 w-full border border-zinc-300 bg-white px-3 py-2.5 font-normal">{values.map(o=><option key={o}>{o}</option>)}</select></label>)}</div><p className="mt-4 text-sm text-zinc-500">{rows.length} check-ins match the current filters. All dashboard values and exports use this selection.</p></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Total visits',rows.length,'Selected period'],['Unique visitors',unique,`${Math.max(0,rows.length-unique)} repeat visits`],['Average traffic',average(daily).toFixed(1),`${average(weekly).toFixed(1)} weekly · ${average(monthly).toFixed(1)} monthly`],['Peak usage',peakHour?.[0]||'-',peakDay?`${peakDay[0]} · ${peakDay[1]} visits`:'No visits']].map(x=><div key={String(x[0])} className="border border-zinc-200 bg-white p-5"><p className="text-sm text-zinc-500">{x[0]}</p><p className="mt-2 text-3xl font-semibold">{x[1]}</p><p className="mt-2 text-xs text-zinc-500">{x[2]}</p></div>)}</section>
 <section className="report-dashboard"><article><h2>Attendance trend</h2><p>Visits grouped {filters.period.toLowerCase()}</p><svg className="line-chart" viewBox="0 0 600 230" preserveAspectRatio="none"><polyline points={trend.map(([,v],i)=>`${trend.length===1?300:i/(trend.length-1)*570+15},${205-v/maxTrend*180}`).join(' ')} fill="none" stroke="#00a5b7" strokeWidth="4" vectorEffect="non-scaling-stroke"/>{trend.map(([k,v],i)=><circle key={k} cx={trend.length===1?300:i/(trend.length-1)*570+15} cy={205-v/maxTrend*180} r="5"><title>{k}: {v} visits</title></circle>)}</svg><div className="chart-labels"><span>{trend[0]?.[0]||'No data'}</span><span>{trend.at(-1)?.[0]||''}</span></div></article><article><h2>User type distribution</h2><p>Student vs. faculty/staff vs. visitor</p><div className="pie-layout"><div className="pie-chart" style={{background:`conic-gradient(${categories.map(([k,v],i)=>{const start=pieStop;pieStop+=v/catTotal*100;return `${['#690f0d','#00a5b7','#e0a72e'][i%3]} ${start}% ${pieStop}%`}).join(',')})`}}/><div>{categories.map(([k,v],i)=><p key={k}><i style={{background:['#690f0d','#00a5b7','#e0a72e'][i%3]}}/><span>{k}</span><strong>{v}</strong></p>)}</div></div></article><article><h2>Top programs</h2><p>Highest library utilization</p><div className="report-bars">{top(programUsage,6).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong><i><b style={{width:`${v/Math.max(1,...programUsage.map(x=>x[1]))*100}%`}}/></i></div>)}</div></article></section>
 <section className="overflow-hidden border border-zinc-200 bg-white"><div className="border-b px-5 py-4"><h2 className="font-semibold">Filtered check-ins</h2><p className="text-xs text-zinc-500">Records included in Excel and PDF exports</p></div><div className="max-h-96 overflow-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="sticky top-0 bg-zinc-50 text-zinc-500"><tr><th className="p-3">Date</th><th>Name</th><th>User type</th><th>Program / Department</th><th>Year / Section</th><th>Check-in time</th><th>Source</th></tr></thead><tbody>{rows.slice(0,80).map(v=><tr className="border-t" key={v.id}><td className="p-3">{v.date}</td><td>{v.visitor}</td><td>{v.userType}</td><td>{v.userType==='Student'?v.program:v.department}</td><td>{[v.yearLevel,v.section].filter(Boolean).join(' / ')||'-'}</td><td>{new Date(v.timeIn).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td><td>{v.source==='manual'?'Manual':'QR'}</td></tr>)}{!rows.length&&<tr><td colSpan={7} className="p-10 text-center text-zinc-500">No records match these filters.</td></tr>}</tbody></table></div></section></div>
}
function drawBars(doc:jsPDF,entries:[string,number][],x:number,y:number,width:number,color:[number,number,number]){const max=Math.max(1,...entries.map(e=>e[1]));entries.slice(0,7).forEach(([k,v],i)=>{const yy=y+i*10;doc.setFontSize(7);doc.setTextColor(60);doc.text(k.slice(0,25),x,yy+4);doc.setFillColor(230,230,230);doc.rect(x+43,yy,width-50,5,'F');doc.setFillColor(...color);doc.rect(x+43,yy,(width-50)*v/max,5,'F');doc.text(String(v),x+width-5,yy+4,{align:'right'})})}
function drawLine(doc:jsPDF,entries:[string,number][],x:number,y:number,width:number,height:number,color:[number,number,number]){doc.setFontSize(11);doc.setTextColor(105,15,13);doc.text('Traffic over selected period',x,y-3);const max=Math.max(1,...entries.map(e=>e[1]));doc.setDrawColor(210);doc.rect(x,y,width,height);doc.setDrawColor(...color);entries.slice(-16).forEach((entry,i,list)=>{if(!i)return;const prev=list[i-1],x1=x+(i-1)/(list.length-1)*width,x2=x+i/(list.length-1)*width,y1=y+height-prev[1]/max*height,y2=y+height-entry[1]/max*height;doc.line(x1,y1,x2,y2)});doc.setFontSize(7);doc.setTextColor(80);if(entries.length){doc.text(entries.at(-16)![0],x,y+height+5);doc.text(entries.at(-1)![0],x+width,y+height+5,{align:'right'})}}










