import React from 'react'
import {BookOpen, Building2, Check, Clock3, FileBarChart, History, Palette, QrCode, RotateCcw, Save, ShieldCheck, UserRoundCog, Users} from 'lucide-react'
import {defaultSettings, getLibrarySettings, LibrarySettings, saveLibrarySettings, SettingsAudit} from './settings'
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean),join=(v:string[])=>v.join(', ')
type ListKey='programs'|'sections'|'yearLevels'|'departments'|'librarians'|'visitorFields'
function Field({label,help,children}:{label:string;help?:string;children:React.ReactNode}){return <label className="settings-field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}
function Section({icon:Icon,title,description,children}:{icon:React.ComponentType<{size?:number}>;title:string;description:string;children:React.ReactNode}){return <section className="settings-section"><header><span className="settings-icon"><Icon size={19}/></span><div><h3>{title}</h3><p>{description}</p></div></header><div className="settings-fields">{children}</div></section>}
export default function SettingsPage(){
 const[settings,setSettings]=React.useState<LibrarySettings>(defaultSettings),[saved,setSaved]=React.useState(false)
 const listValues=(s:LibrarySettings):Record<ListKey,string>=>({programs:join(s.programs),sections:join(s.sections),yearLevels:join(s.yearLevels),departments:join(s.departments),librarians:join(s.librarians),visitorFields:join(s.visitorFields)})
 const[listText,setListText]=React.useState<Record<ListKey,string>>(()=>listValues(defaultSettings))
 const[audit,setAudit]=React.useState<SettingsAudit[]>([])
 const[loading,setLoading]=React.useState(true),[saving,setSaving]=React.useState(false),[error,setError]=React.useState(''),[legacy,setLegacy]=React.useState(false)
 React.useEffect(()=>{let active=true;getLibrarySettings().then(result=>{if(!active)return;let values=result.settings;if(!result.configured){try{const stored=localStorage.getItem('library-settings');if(stored){values={...values,...JSON.parse(stored)};const oldTypes:Record<string,string>={Student:'student',Faculty:'faculty','Non-Teaching':'non-teaching personnel',Visitor:'visitor'};values.defaultReportUserType=oldTypes[values.defaultReportUserType]||values.defaultReportUserType;setLegacy(true)}}catch{}}setSettings(values);setListText(listValues(values));setAudit(result.audit)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load settings')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const set=<K extends keyof LibrarySettings>(key:K,value:LibrarySettings[K])=>{setSaved(false);setSettings(s=>({...s,[key]:value}))}
 async function submit(e:React.FormEvent){e.preventDefault();const normalized={...settings,...Object.fromEntries(Object.entries(listText).map(([key,value])=>[key,split(value)]))} as LibrarySettings;setSaving(true);setError('');try{const result=await saveLibrarySettings(normalized);setSettings(result.settings);setAudit(result.audit);setSaved(true);setLegacy(false);localStorage.removeItem('library-settings');localStorage.removeItem('settings-audit');setTimeout(()=>setSaved(false),2500)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save settings')}finally{setSaving(false)}}
 return <form className="settings-page" onSubmit={submit}><div className="settings-intro"><div><h2>Administration</h2><p>Configure attendance rules, school data, reporting, and the student QR display.</p></div><div className="settings-actions"><button type="button" className="secondary-button" disabled={loading||saving} onClick={()=>{setSettings(defaultSettings);setListText(listValues(defaultSettings));setSaved(false)}}><RotateCcw size={16}/>Reset</button><button className="save-button" disabled={loading||saving}><Save size={16}/>{saving?'Saving...':saved?'Saved':'Save changes'}</button></div></div>{loading&&<p role="status">Loading settings...</p>}{error&&<p role="alert" className="settings-error">{error}</p>}{legacy&&<p role="status" className="settings-note">Browser-saved settings found. Review and save to move them to the shared backend.</p>}<div className="settings-grid">
 <Section icon={Clock3} title="Library operations" description="Record the service schedule; attendance hours are not enforced yet."><Field label="Library name"><input value={settings.libraryName} onChange={e=>set('libraryName',e.target.value)} required/></Field><Field label="Timezone"><select value={settings.timezone} onChange={e=>set('timezone',e.target.value)}><option>Asia/Manila</option><option>UTC</option></select></Field><Field label="Opening time"><input type="time" value={settings.opensAt} onChange={e=>set('opensAt',e.target.value)}/></Field><Field label="Closing time"><input type="time" value={settings.closesAt} onChange={e=>set('closesAt',e.target.value)}/></Field></Section>
 <Section icon={QrCode} title="QR attendance" description="Control daily code rotation and repeat scans."><div className="settings-note"><QrCode size={18}/><span>A new QR code is generated automatically every day at midnight.</span></div><Field label="Duplicate scan window (minutes)"><input type="number" min="1" max="60" value={settings.duplicateWindowMinutes} onChange={e=>set('duplicateWindowMinutes',Number(e.target.value))}/></Field></Section>
 <Section icon={BookOpen} title="Academic calendar" description="Record the current term; historical reports derive terms from visit dates."><Field label="Current academic year"><input value={settings.academicYear} onChange={e=>set('academicYear',e.target.value)} required/></Field><Field label="Current semester"><select value={settings.semester} onChange={e=>set('semester',e.target.value)}><option>1st Semester</option><option>2nd Semester</option><option>Summer</option></select></Field></Section>
 <Section icon={Building2} title="School structure" description="Saved reference lists; report filters currently use values from user profiles."><Field label="Degree programs"><textarea value={listText.programs} onChange={e=>{setSaved(false);setListText(v=>({...v,programs:e.target.value}))}}/></Field><Field label="Sections"><textarea value={listText.sections} onChange={e=>{setSaved(false);setListText(v=>({...v,sections:e.target.value}))}}/></Field><Field label="Year levels"><textarea value={listText.yearLevels} onChange={e=>{setSaved(false);setListText(v=>({...v,yearLevels:e.target.value}))}}/></Field><Field label="Departments"><textarea value={listText.departments} onChange={e=>{setSaved(false);setListText(v=>({...v,departments:e.target.value}))}}/></Field></Section>
 <Section icon={UserRoundCog} title="Librarian access" description="Record planned administrator roles."><Field label="Librarian roles" help="Saved for planning; this list does not grant account access."><textarea value={listText.librarians} onChange={e=>{setSaved(false);setListText(v=>({...v,librarians:e.target.value}))}}/></Field><div className="settings-note"><ShieldCheck size={18}/><span>Librarian access is managed through backend accounts, not this list.</span></div></Section>
 <Section icon={Users} title="Visitor registration" description="Record the planned guest information fields."><Field label="Visitor fields" help="Saved for planning; the guest form currently collects name, organization, and purpose."><textarea value={listText.visitorFields} onChange={e=>{setSaved(false);setListText(v=>({...v,visitorFields:e.target.value}))}}/></Field></Section>
 <Section icon={FileBarChart} title="Report defaults" description="Set the initial filters when librarians open Reports."><Field label="Default period"><select value={settings.defaultReportPeriod} onChange={e=>set('defaultReportPeriod',e.target.value)}><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Annual</option></select></Field><Field label="Default user type"><select value={settings.defaultReportUserType} onChange={e=>set('defaultReportUserType',e.target.value)}><option value="All">All</option><option value="student">Student</option><option value="faculty">Faculty</option><option value="non-teaching personnel">Non-Teaching Personnel</option><option value="administrator">Administrator</option><option value="visitor">Visitor</option></select></Field></Section>
 <Section icon={ShieldCheck} title="Data retention" description="Record the intended retention policy."><Field label="Keep attendance records (years)"><input type="number" min="1" max="10" value={settings.retentionYears} onChange={e=>set('retentionYears',Number(e.target.value))}/></Field><div className="settings-note"><ShieldCheck size={18}/><span>Automatic deletion is not active yet.</span></div></Section>
 <Section icon={Palette} title="QR display" description="Customize wording students see at the entrance."><Field label="Display heading"><input value={settings.qrHeading} onChange={e=>set('qrHeading',e.target.value)} maxLength={70}/></Field><Field label="Instructions"><textarea value={settings.qrInstructions} onChange={e=>set('qrInstructions',e.target.value)} maxLength={220}/></Field><Field label="Room booking link"><input type="url" value={settings.roomBookingUrl||''} onChange={e=>set('roomBookingUrl',e.target.value)} placeholder="https://"/><small>Shared booking page for Nap Rooms and Collaboration Rooms.</small></Field></Section>
 <Section icon={History} title="Audit history" description="Recent administrative settings activity.">{audit.length?<div className="audit-list">{audit.slice(0,5).map(i=><div key={i.id}><span className="audit-check"><Check size={13}/></span><span><strong>{i.action}</strong><small>{i.user} · {new Date(i.at).toLocaleString()}</small></span></div>)}</div>:<div className="settings-empty">No settings changes recorded yet.</div>}</Section>
 </div></form>}
