import React from 'react'
import {BookOpen, Building2, Check, FileBarChart, History, Palette, QrCode, RotateCcw, Save} from 'lucide-react'
import {defaultSettings, getLibrarySettings, LibrarySettings, saveLibrarySettings, SettingsAudit} from './settings'
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean),join=(v:string[])=>v.join(', ')
type ListKey='programs'|'sections'|'yearLevels'|'departments'|'librarians'|'visitorFields'
function Field({label,help,children}:{label:string;help?:string;children:React.ReactNode}){return <label className="settings-field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}
function NumberInput({value,min,max,onChange}:{value:number;min:number;max:number;onChange:(value:number)=>void}){
 const[text,setText]=React.useState(String(value))
 React.useEffect(()=>setText(String(value)),[value])
 return <input className="settings-number-input" type="text" inputMode="numeric" pattern="[0-9]*" value={text} onChange={event=>{const next=event.target.value.replace(/\D/g,'');setText(next);if(next!=='')onChange(Number(next))}} onBlur={()=>{if(text===''){setText(String(value));return}const bounded=Math.min(max,Math.max(min,Number(text)));setText(String(bounded));onChange(bounded)}} aria-label={`Enter a number from ${min} to ${max}`}/>
}
function Section({icon:Icon,title,description,children}:{icon:React.ComponentType<{size?:number}>;title:string;description:string;children:React.ReactNode}){return <section className="settings-section"><header><span className="settings-icon"><Icon size={19}/></span><div><h3>{title}</h3><p>{description}</p></div></header><div className="settings-fields">{children}</div></section>}
const auditLabel=(value:string)=>value.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,letter=>letter.toUpperCase())
const auditValue=(value:unknown)=>value===undefined||value===null||value===''?'Not set':Array.isArray(value)?value.join(', '):String(value)
function AuditEntry({item}:{item:SettingsAudit}){
 const fields=item.changedFields||[]
 return <div className="audit-entry"><span className="audit-check"><Check size={13}/></span><span className="audit-entry-body"><strong>{item.action}</strong><small>{item.user}{item.actorEmail?` (${item.actorEmail})`:''} · {new Date(item.at).toLocaleString()}</small>{fields.length?<details className="audit-details"><summary>{fields.length} field{fields.length===1?'':'s'} changed</summary><dl>{fields.map(field=><div key={field}><dt>{auditLabel(field)}</dt><dd><span>{auditValue(item.beforeValues?.[field])}</span><b>to</b><span>{auditValue(item.afterValues?.[field])}</span></dd></div>)}</dl></details>:<small>Legacy entry; before-and-after values were not recorded.</small>}</span></div>
}
export default function SettingsPage(){
 const[settings,setSettings]=React.useState<LibrarySettings>(defaultSettings),[saved,setSaved]=React.useState(false)
 const listValues=(s:LibrarySettings):Record<ListKey,string>=>({programs:join(s.programs),sections:join(s.sections),yearLevels:join(s.yearLevels),departments:join(s.departments),librarians:join(s.librarians),visitorFields:join(s.visitorFields)})
 const[listText,setListText]=React.useState<Record<ListKey,string>>(()=>listValues(defaultSettings))
 const[audit,setAudit]=React.useState<SettingsAudit[]>([])
 const[loading,setLoading]=React.useState(true),[saving,setSaving]=React.useState(false),[error,setError]=React.useState(''),[legacy,setLegacy]=React.useState(false)
 React.useEffect(()=>{let active=true;getLibrarySettings().then(result=>{if(!active)return;let values=result.settings;if(!result.configured){try{const stored=localStorage.getItem('library-settings');if(stored){values={...values,...JSON.parse(stored)};const oldTypes:Record<string,string>={Student:'student',Faculty:'faculty','Non-Teaching':'non-teaching personnel',Visitor:'visitor'};values.defaultReportUserType=oldTypes[values.defaultReportUserType]||values.defaultReportUserType;setLegacy(true)}}catch{}}setSettings(values);setListText(listValues(values));setAudit(result.audit)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load settings')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const set=<K extends keyof LibrarySettings>(key:K,value:LibrarySettings[K])=>{setSaved(false);setSettings(s=>({...s,[key]:value}))}
 async function submit(e:React.FormEvent){e.preventDefault();const normalized={...settings,...Object.fromEntries(Object.entries(listText).map(([key,value])=>[key,split(value)]))} as LibrarySettings;setSaving(true);setError('');try{const result=await saveLibrarySettings(normalized);setSettings(result.settings);setAudit(result.audit);setSaved(true);setLegacy(false);localStorage.removeItem('library-settings');localStorage.removeItem('settings-audit');setTimeout(()=>setSaved(false),2500)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save settings')}finally{setSaving(false)}}
 return <form className="settings-page" onSubmit={submit}><div className="settings-intro"><div><h2>Administration</h2><p>Configure active attendance rules, school data, reporting, and the student QR display.</p></div><div className="settings-actions"><button type="button" className="secondary-button" disabled={loading||saving} onClick={()=>{setSettings(defaultSettings);setListText(listValues(defaultSettings));setSaved(false)}}><RotateCcw size={16}/>Reset</button><button className="save-button" disabled={loading||saving}><Save size={16}/>{saving?'Saving...':saved?'Saved':'Save changes'}</button></div></div>{loading&&<p role="status">Loading settings...</p>}{error&&<p role="alert" className="settings-error">{error}</p>}{legacy&&<p role="status" className="settings-note">Browser-saved settings found. Review and save to move them to the shared backend.</p>}<div className="settings-grid">
 <Section icon={BookOpen} title="Library profile" description="Set the library name displayed on the student QR screen."><Field label="Library name"><input value={settings.libraryName} onChange={e=>set('libraryName',e.target.value)} required/></Field></Section>
 <Section icon={QrCode} title="QR attendance" description="Control daily code rotation and repeat scans."><div className="settings-note"><QrCode size={18}/><span>A new QR code is generated automatically every day at midnight.</span></div><Field label="Duplicate scan window (minutes)"><NumberInput value={settings.duplicateWindowMinutes} min={1} max={60} onChange={value=>set('duplicateWindowMinutes',value)}/></Field></Section>
 <Section icon={FileBarChart} title="Report defaults" description="Set the initial filters when librarians open Reports."><Field label="Default period"><select value={settings.defaultReportPeriod} onChange={e=>set('defaultReportPeriod',e.target.value)}><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Annual</option></select></Field><Field label="Default user type"><select value={settings.defaultReportUserType} onChange={e=>set('defaultReportUserType',e.target.value)}><option value="All">All</option><option value="student">Student</option><option value="faculty">Faculty</option><option value="non-teaching personnel">Non-Teaching Personnel</option><option value="administrator">Administrator</option><option value="visitor">Visitor</option></select></Field></Section>
 <Section icon={Palette} title="QR display" description="Customize wording students see at the entrance."><Field label="Display heading"><input value={settings.qrHeading} onChange={e=>set('qrHeading',e.target.value)} maxLength={70}/></Field><Field label="Instructions"><textarea value={settings.qrInstructions} onChange={e=>set('qrInstructions',e.target.value)} maxLength={220}/></Field><Field label="Room booking link"><input type="url" value={settings.roomBookingUrl||''} onChange={e=>set('roomBookingUrl',e.target.value)} placeholder="https://"/><small>Shared booking page for Nap Rooms and Collaboration Rooms.</small></Field></Section>
 <Section icon={Building2} title="School structure" description="Comma-separated values saved here become the choices in Library User forms and report filters."><Field label="Degree programs"><textarea value={listText.programs} onChange={e=>{setSaved(false);setListText(v=>({...v,programs:e.target.value}))}}/></Field><Field label="Sections"><textarea value={listText.sections} onChange={e=>{setSaved(false);setListText(v=>({...v,sections:e.target.value}))}}/></Field><Field label="Year levels"><textarea value={listText.yearLevels} onChange={e=>{setSaved(false);setListText(v=>({...v,yearLevels:e.target.value}))}}/></Field><Field label="Departments"><textarea value={listText.departments} onChange={e=>{setSaved(false);setListText(v=>({...v,departments:e.target.value}))}}/></Field></Section>
 <Section icon={History} title="Audit history" description="Who changed settings, when, and the values before and after.">{audit.length?<div className="audit-list">{audit.slice(0,5).map(item=><AuditEntry key={item.id} item={item}/>)}</div>:<div className="settings-empty">No settings changes recorded yet.</div>}</Section>
 </div></form>}
