import React from 'react'
import {BookOpen, Building2, Check, Clock3, FileBarChart, History, Palette, QrCode, RotateCcw, Save, ShieldCheck, UserRoundCog, Users} from 'lucide-react'
import {defaultSettings, LibrarySettings, loadSettings, saveSettings} from './settings'
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean),join=(v:string[])=>v.join(', ')
type ListKey='programs'|'sections'|'yearLevels'|'departments'|'librarians'|'visitorFields'
function Field({label,help,children}:{label:string;help?:string;children:React.ReactNode}){return <label className="settings-field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}
function Section({icon:Icon,title,description,children}:{icon:React.ComponentType<{size?:number}>;title:string;description:string;children:React.ReactNode}){return <section className="settings-section"><header><span className="settings-icon"><Icon size={19}/></span><div><h3>{title}</h3><p>{description}</p></div></header><div className="settings-fields">{children}</div></section>}
export default function SettingsPage(){
 const[settings,setSettings]=React.useState<LibrarySettings>(loadSettings),[saved,setSaved]=React.useState(false)
 const[listText,setListText]=React.useState<Record<ListKey,string>>(()=>{const s=loadSettings();return{programs:join(s.programs),sections:join(s.sections),yearLevels:join(s.yearLevels),departments:join(s.departments),librarians:join(s.librarians),visitorFields:join(s.visitorFields)}})
 const[audit,setAudit]=React.useState<{id:string;action:string;user:string;at:string}[]>(()=>JSON.parse(localStorage.getItem('settings-audit')||'[]'))
 const set=<K extends keyof LibrarySettings>(key:K,value:LibrarySettings[K])=>{setSaved(false);setSettings(s=>({...s,[key]:value}))}
 function submit(e:React.FormEvent){e.preventDefault();const normalized={...settings,...Object.fromEntries(Object.entries(listText).map(([key,value])=>[key,split(value)]))} as LibrarySettings;setSettings(normalized);saveSettings(normalized);setAudit(JSON.parse(localStorage.getItem('settings-audit')||'[]'));setSaved(true);setTimeout(()=>setSaved(false),2500)}
 return <form className="settings-page" onSubmit={submit}><div className="settings-intro"><div><span className="eyebrow">Administration</span><h2>Library settings</h2><p>Configure attendance rules, school data, reporting, and the student QR display.</p></div><div className="settings-actions"><button type="button" className="secondary-button" onClick={()=>{setSettings(defaultSettings);setListText({programs:join(defaultSettings.programs),sections:join(defaultSettings.sections),yearLevels:join(defaultSettings.yearLevels),departments:join(defaultSettings.departments),librarians:join(defaultSettings.librarians),visitorFields:join(defaultSettings.visitorFields)});setSaved(false)}}><RotateCcw size={16}/>Reset</button><button className="save-button"><Save size={16}/>{saved?'Saved':'Save changes'}</button></div></div><div className="settings-grid">
 <Section icon={Clock3} title="Library operations" description="Set the service schedule used by attendance workflows."><Field label="Library name"><input value={settings.libraryName} onChange={e=>set('libraryName',e.target.value)} required/></Field><Field label="Timezone"><select value={settings.timezone} onChange={e=>set('timezone',e.target.value)}><option>Asia/Manila</option><option>UTC</option></select></Field><Field label="Opening time"><input type="time" value={settings.opensAt} onChange={e=>set('opensAt',e.target.value)}/></Field><Field label="Closing time"><input type="time" value={settings.closesAt} onChange={e=>set('closesAt',e.target.value)}/></Field></Section>
 <Section icon={QrCode} title="QR attendance" description="Control code validity and repeat scans."><Field label="QR validity (minutes)" help="1,440 minutes keeps a code active for one day."><input type="number" min="5" max="10080" value={settings.qrExpiryMinutes} onChange={e=>set('qrExpiryMinutes',Number(e.target.value))}/></Field><Field label="Duplicate scan window (minutes)"><input type="number" min="1" max="60" value={settings.duplicateWindowMinutes} onChange={e=>set('duplicateWindowMinutes',Number(e.target.value))}/></Field></Section>
 <Section icon={BookOpen} title="Academic calendar" description="Choose the active attendance term."><Field label="Current academic year"><input value={settings.academicYear} onChange={e=>set('academicYear',e.target.value)} required/></Field><Field label="Current semester"><select value={settings.semester} onChange={e=>set('semester',e.target.value)}><option>1st Semester</option><option>2nd Semester</option><option>Summer</option></select></Field></Section>
 <Section icon={Building2} title="School structure" description="Comma-separated values populate user and report choices."><Field label="Degree programs"><textarea value={listText.programs} onChange={e=>{setSaved(false);setListText(v=>({...v,programs:e.target.value}))}}/></Field><Field label="Sections"><textarea value={listText.sections} onChange={e=>{setSaved(false);setListText(v=>({...v,sections:e.target.value}))}}/></Field><Field label="Year levels"><textarea value={listText.yearLevels} onChange={e=>{setSaved(false);setListText(v=>({...v,yearLevels:e.target.value}))}}/></Field><Field label="Departments"><textarea value={listText.departments} onChange={e=>{setSaved(false);setListText(v=>({...v,departments:e.target.value}))}}/></Field></Section>
 <Section icon={UserRoundCog} title="Librarian access" description="Define the administrator roles for this tenant."><Field label="Librarian roles" help="Account invitations will be enabled with the backend."><textarea value={listText.librarians} onChange={e=>{setSaved(false);setListText(v=>({...v,librarians:e.target.value}))}}/></Field><div className="settings-note"><ShieldCheck size={18}/><span>Google authentication remains limited to users scanning the attendance QR.</span></div></Section>
 <Section icon={Users} title="Visitor registration" description="Choose the information collected from guests."><Field label="Required visitor fields"><textarea value={listText.visitorFields} onChange={e=>{setSaved(false);setListText(v=>({...v,visitorFields:e.target.value}))}}/></Field></Section>
 <Section icon={FileBarChart} title="Report defaults" description="Set the initial filters when librarians open Reports."><Field label="Default period"><select value={settings.defaultReportPeriod} onChange={e=>set('defaultReportPeriod',e.target.value)}><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Annual</option></select></Field><Field label="Default user type"><select value={settings.defaultReportUserType} onChange={e=>set('defaultReportUserType',e.target.value)}><option>All</option><option>Student</option><option>Faculty</option><option>Non-Teaching</option><option>Visitor</option></select></Field></Section>
 <Section icon={ShieldCheck} title="Data retention" description="Set the policy for historical attendance records."><Field label="Keep attendance records (years)"><input type="number" min="1" max="10" value={settings.retentionYears} onChange={e=>set('retentionYears',Number(e.target.value))}/></Field><div className="settings-note"><ShieldCheck size={18}/><span>Automatic deletion will run after backend storage is connected.</span></div></Section>
 <Section icon={Palette} title="QR display" description="Customize wording students see at the entrance."><Field label="Display heading"><input value={settings.qrHeading} onChange={e=>set('qrHeading',e.target.value)} maxLength={70}/></Field><Field label="Instructions"><textarea value={settings.qrInstructions} onChange={e=>set('qrInstructions',e.target.value)} maxLength={220}/></Field></Section>
 <Section icon={History} title="Audit history" description="Recent administrative settings activity.">{audit.length?<div className="audit-list">{audit.slice(0,5).map(i=><div key={i.id}><span className="audit-check"><Check size={13}/></span><span><strong>{i.action}</strong><small>{i.user} · {new Date(i.at).toLocaleString()}</small></span></div>)}</div>:<div className="settings-empty">No settings changes recorded yet.</div>}</Section>
 </div></form>}


