import React from 'react'
import {ArrowLeft, CalendarDays, Clock3, Eye, Search, UserRound, Users} from 'lucide-react'
import {getAllVisits} from './attendanceStore'

export default function Students(){
 const[q,setQ]=React.useState(''),visits=React.useMemo(getAllVisits,[])
 const profiles=React.useMemo(()=>Array.from(new Set(visits.map(v=>v.studentNumber))).map(number=>{const rows=visits.filter(v=>v.studentNumber===number),latest=[...rows].sort((a,b)=>b.timeIn.localeCompare(a.timeIn))[0];return{name:latest.visitor,number,userType:latest.userType,program:latest.program,yearLevel:latest.yearLevel,section:latest.section,department:latest.department,visits:rows.length,lastVisit:latest.timeIn}}).filter(p=>(p.name+' '+p.number+' '+p.program+' '+p.department).toLowerCase().includes(q.toLowerCase())),[q,visits])
 return <div className="module-stack directory-page"><div className="module-heading"><div><span className="eyebrow">Directory</span><h2>Students and library users</h2><p>Open a profile to review the user’s complete library visit history.</p></div><div className="module-count"><Users size={18}/><strong>{profiles.length}</strong><span>profiles</span></div></div><section className="panel"><label className="module-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, number, program, or department"/></label><div className="table-wrap"><table><thead><tr><th>User</th><th>Type</th><th>Program / Department</th><th>Year / Section</th><th>Visits</th><th>Last visit</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{profiles.map(p=><tr key={p.number} className="profile-row" onDoubleClick={()=>location.assign('/students/'+encodeURIComponent(p.number))}><td><strong>{p.name}</strong><small>{p.number}</small></td><td><span className="badge user-type-badge">{p.userType}</span></td><td>{p.program||p.department||'External visitor'}</td><td>{p.yearLevel&&p.section?p.yearLevel+' / '+p.section:'-'}</td><td><strong>{p.visits}</strong></td><td>{new Date(p.lastVisit).toLocaleDateString()}</td><td><button className="row-action" title={`View visits for ${p.name}`} onClick={()=>location.assign('/students/'+encodeURIComponent(p.number))}><Eye size={17}/></button></td></tr>)}</tbody></table></div></section></div>
}

export function StudentDetail({number}:{number:string}){
 const all=React.useMemo(getAllVisits,[]),rows=React.useMemo(()=>all.filter(v=>v.studentNumber===number).sort((a,b)=>b.timeIn.localeCompare(a.timeIn)),[all,number]),profile=rows[0]
 if(!profile)return <div className="module-stack directory-page"><button className="back-button" onClick={()=>location.assign('/students')}><ArrowLeft size={17}/>Back to directory</button><section className="panel empty-profile"><UserRound size={34}/><h2>User not found</h2><p>No attendance profile matches this ID number.</p></section></div>
 const detail=profile.userType==='Student'?[profile.program,profile.yearLevel,profile.section].filter(Boolean).join(' · '):profile.department||'External visitor',days=new Set(rows.map(v=>v.date)).size
 return <div className="module-stack directory-page"><button className="back-button" onClick={()=>location.assign('/students')}><ArrowLeft size={17}/>Back to directory</button><section className="profile-hero panel"><span className="profile-avatar">{profile.visitor.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><span className="eyebrow">{profile.userType} profile</span><h2>{profile.visitor}</h2><p>{profile.studentNumber} · {detail}</p></div></section><section className="profile-metrics"><div className="metric-card"><span>Total visits</span><strong>{rows.length}</strong><small>All recorded check-ins</small></div><div className="metric-card"><span>Days visited</span><strong>{days}</strong><small>Distinct library dates</small></div><div className="metric-card"><span>Latest visit</span><strong className="metric-date">{new Date(profile.timeIn).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</strong><small>{new Date(profile.timeIn).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div></section><section className="panel"><div className="panel-title"><div><Clock3 size={18}/><h3>Library visit history</h3></div><span>{rows.length} check-ins</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Check-in time</th><th>Academic year</th><th>Semester</th><th>Source</th><th>Note</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td><strong>{new Date(v.date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</strong></td><td>{new Date(v.timeIn).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td><td>{v.academicYear}</td><td>{v.semester}</td><td><span className={v.source==='manual'?'badge manual':'badge inside'}>{v.source==='manual'?'Manual':'QR'}</span></td><td>{v.note||'-'}</td></tr>)}</tbody></table></div></section><section className="profile-footnote"><CalendarDays size={16}/><span>Visit totals follow the same shared records used by Attendance and Reports.</span></section></div>
}
