import React from 'react'
import {ArrowLeft, CalendarDays, Clock3, Eye, Pencil, Plus, Search, UserRound, Users} from 'lucide-react'
import {apiRequest,ApiUser,ApiVisit,displayUserType,Page} from './api'
import UserEditor from './UserEditor'

const BASE=import.meta.env.BASE_URL
const href=(path:string)=>BASE+(path==='/'?'':path.replace(/^\//,''))

export default function Students({canManage=false}:{canManage?:boolean}){
 const[q,setQ]=React.useState(''),[profiles,setProfiles]=React.useState<ApiUser[]>([]),[total,setTotal]=React.useState(0),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true)
 const[refresh,setRefresh]=React.useState(0),[editing,setEditing]=React.useState<ApiUser|null|undefined>(undefined)
 React.useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setLoading(true);apiRequest<Page<ApiUser>>('/api/library/users?'+new URLSearchParams({q,page_size:'200'}),{signal:controller.signal}).then(body=>{setProfiles(body.items);setTotal(body.total);setError('')}).catch(reason=>{if(reason.name!=='AbortError')setError(reason.message)}).finally(()=>setLoading(false))},200);return()=>{clearTimeout(timer);controller.abort()}},[q,refresh])
 return <div className="module-stack directory-page"><div className="module-heading"><div><h2>Directory</h2><p>Open a profile to review the user’s complete library visit history.</p></div><div className="module-count"><Users size={18}/><strong>{total}</strong><span>profiles</span></div></div><section className="panel"><div className="directory-toolbar"><label className="module-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, number, program, or department"/></label>{canManage&&<button className="manual-button" onClick={()=>setEditing(null)}><Plus size={17}/>Add User</button>}</div>{error&&<p className="module-error">{error}</p>}<div className="table-wrap"><table><thead><tr><th>User</th><th>Type</th><th>Program / Department</th><th>Year / Section</th><th>Visits</th><th>Last visit</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{profiles.map(p=><tr key={p.number} className="profile-row" onDoubleClick={()=>location.assign(href('/students/'+encodeURIComponent(p.number)))}><td><strong>{p.name}</strong><small>{p.number}</small></td><td><span className="badge user-type-badge">{displayUserType(p.user_type)}</span></td><td>{p.program||p.department||p.organization||'External visitor'}</td><td>{[p.year_level,p.section].filter(Boolean).join(' / ')||'-'}</td><td><strong>{p.visit_count}</strong></td><td>{p.last_visit?new Date(p.last_visit).toLocaleDateString():'-'}</td><td><div className="directory-row-actions"><button className="row-action" title={`View visits for ${p.name}`} onClick={()=>location.assign(href('/students/'+encodeURIComponent(p.number)))}><Eye size={17}/></button>{canManage&&<button className="row-action" title={`Edit ${p.name}`} onClick={()=>setEditing(p)}><Pencil size={17}/></button>}</div></td></tr>)}</tbody></table>{loading&&<p className="module-state">Loading library users...</p>}{!loading&&!profiles.length&&!error&&<p className="module-state">No library users match this search.</p>}</div></section>{editing!==undefined&&<UserEditor user={editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);setRefresh(value=>value+1)}}/>}</div>
}

export function StudentDetail({number}:{number:string}){
 const[profile,setProfile]=React.useState<ApiUser|null>(null),[rows,setRows]=React.useState<ApiVisit[]>([]),[loading,setLoading]=React.useState(true),[error,setError]=React.useState('')
 React.useEffect(()=>{Promise.all([apiRequest<ApiUser>('/api/library/users/'+encodeURIComponent(number)),apiRequest<Page<ApiVisit>>('/api/library/users/'+encodeURIComponent(number)+'/visits')]).then(([user,visits])=>{setProfile(user);setRows(visits.items)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[number])
 if(loading)return <div className="module-stack directory-page"><p className="module-state">Loading visit history...</p></div>
 if(!profile)return <div className="module-stack directory-page"><button className="back-button" onClick={()=>location.assign(href('/students'))}><ArrowLeft size={17}/>Back to directory</button><section className="panel empty-profile"><UserRound size={34}/><h2>User not found</h2><p>{error||'No attendance profile matches this ID number.'}</p></section></div>
 const detail=profile.user_type==='student'?[profile.program,profile.year_level,profile.section].filter(Boolean).join(' · '):profile.department||profile.organization||'External visitor',days=new Set(rows.map(v=>new Date(v.check_in_time).toDateString())).size
 return <div className="module-stack directory-page"><button className="back-button" onClick={()=>location.assign(href('/students'))}><ArrowLeft size={17}/>Back to directory</button><section className="profile-hero panel"><span className="profile-avatar">{profile.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><span className="eyebrow">{displayUserType(profile.user_type)} profile</span><h2>{profile.name}</h2><p>{profile.number} · {detail}</p></div></section><section className="profile-metrics"><div className="metric-card"><span>Total visits</span><strong>{rows.length}</strong><small>All recorded check-ins</small></div><div className="metric-card"><span>Days visited</span><strong>{days}</strong><small>Distinct library dates</small></div><div className="metric-card"><span>Latest visit</span><strong className="metric-date">{rows[0]?new Date(rows[0].check_in_time).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'-'}</strong><small>{rows[0]?new Date(rows[0].check_in_time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'No visits'}</small></div></section><section className="panel"><div className="panel-title"><div><Clock3 size={18}/><h3>Library visit history</h3></div><span>{rows.length} check-ins</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Check-in time</th><th>Source</th><th>Purpose / Note</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td><strong>{new Date(v.check_in_time).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</strong></td><td>{new Date(v.check_in_time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td><td><span className={v.source==='manual'?'badge manual':'badge inside'}>{v.source==='manual'?'Manual':v.source==='guest'?'Guest QR':'QR'}</span></td><td>{v.purpose||v.note||'-'}</td></tr>)}</tbody></table></div></section><section className="profile-footnote"><CalendarDays size={16}/><span>Visit totals use the same database records shown in Attendance.</span></section></div>
}
