"""create initial attendance schema

Revision ID: fbc5614d6f66
Revises: 
Create Date: 2026-09-10 16:49:24.209120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc5614d6f66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('librarians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_librarians_email'), 'librarians', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('library_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['librarians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_sessions_session_date'), 'library_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_library_sessions_status'), 'library_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_library_sessions_token_hash'), 'library_sessions', ['token_hash'], unique=True)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=50), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('program', sa.String(length=120), nullable=True),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_student_number'), 'student_profiles', ['student_number'], unique=True)
    op.create_table('library_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('library_session_id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('adjusted_by', sa.Integer(), nullable=True),
    sa.Column('adjustment_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by'], ['librarians.id'], ),
    sa.ForeignKeyConstraint(['library_session_id'], ['library_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_visits_library_session_id'), 'library_visits', ['library_session_id'], unique=False)
    op.create_index(op.f('ix_library_visits_status'), 'library_visits', ['status'], unique=False)
    op.create_index(op.f('ix_library_visits_student_profile_id'), 'library_visits', ['student_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_visits_student_profile_id'), table_name='library_visits')
    op.drop_index(op.f('ix_library_visits_status'), table_name='library_visits')
    op.drop_index(op.f('ix_library_visits_library_session_id'), table_name='library_visits')
    op.drop_table('library_visits')
    op.drop_index(op.f('ix_student_profiles_student_number'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_library_sessions_token_hash'), table_name='library_sessions')
    op.drop_index(op.f('ix_library_sessions_status'), table_name='library_sessions')
    op.drop_index(op.f('ix_library_sessions_session_date'), table_name='library_sessions')
    op.drop_table('library_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_librarians_email'), table_name='librarians')
    op.drop_table('librarians')
    # ### end Alembic commands ###
